MKDIR "C:\Dropbox (LIG Marine)"
MKLINK /D "C:\Dropbox (LIG Marine)\ToQuote" "C:\LIG Marine Dropbox\ToQuote"
MKLINK /D "C:\Dropbox (LIG Marine)\Company" "C:\LIG Marine Dropbox\Company"
MKLINK /D "C:\Dropbox (LIG Marine)\LIG" "C:\LIG Marine Dropbox\LIG"
MKLINK /D "C:\Dropbox (LIG Marine)\TeamFolder" "C:\LIG Marine Dropbox\TeamFolder"
MKLINK /D "C:\Dropbox (LIG Marine)\Apps" "C:\LIG Marine Dropbox\Apps"
MKLINK /D "C:\Dropbox (LIG Marine)\Engines" "C:\LIG Marine Dropbox\Engines"
MKLINK /D "C:\Dropbox (LIG Marine)\PolicyDelivery" "C:\LIG Marine Dropbox\PolicyDelivery"
MKLINK /D "C:\Dropbox (LIG Marine)\Procedures" "C:\LIG Marine Dropbox\Procedures"
MKLINK /D "C:\Dropbox (LIG Marine)\ResourcePro" "C:\LIG Marine Dropbox\ResourcePro"